name: Deploy to gh-pages

on:
  push:
    branches: [ develop, master, feature-ember-update ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Tune ssh-keys
      env:
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        set -x
        export ENCRYPTION_KEY
        #  Recover private key
        openssl aes-256-cbc -in .github/workflows/secrets/id_rsa.enc -out .github/workflows/secrets/id_rsa -pass pass:$ENCRYPTION_KEY -d -md sha1
        # Setup SSH agent
        export SSH_AUTH_SOCK=/tmp/ssh_agent.sock
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        # Start ssh agent
        ssh-agent -a $SSH_AUTH_SOCK #> /dev/null
        chmod 0600 .github/workflows/secrets/id_rsa
        ssh-add .github/workflows/secrets/id_rsa

    - name: Update documentation
      run: |
        ifs=$IFS; IFS=/; set -- $GITHUB_REF; IFS=$ifs; while [ $# -gt 1 ]; do shift; done;
        export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
        export SSH_AUTH_SOCK=/tmp/ssh_agent.sock
        export TRAVIS_BRANCH=$1
        export GH_TOKEN=${{ secrets.GITHUB_TOKEN }}
        bash scripts/update-docs.sh
        exit 0

